logging:
  level:
    org:
      springframework: DEBUG
app:
  msg:
    welcome: "Welcome to the PROD profile"

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true